services:
  app:
    build: .
    env_file: ./env.docker
    ports:
      - '3004:3004'

  mongo:
    image: mongo
    ports:
      - '27014:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    ports:
      - '8084:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
volumes:
  data: {}
